- network: Github
  username: sixFingers
  link: https://github.com/sixFingers

- network: StackOverflow
  username: sixfingers
  link: https://stackoverflow.com/users/472179/sixfingers

- network: Reddit
  username: intAligned
  link: https://www.reddit.com/user/intAligned/

- network: LinkedIn
  username: ignaziosetti
  link: https://fr.linkedin.com/in/ignaziosetti
